//
// Created by Yasuoki on 2025/12/16.
//

#ifndef SLAPPYBELL_FIRMWARE_CONFIG_H
#define SLAPPYBELL_FIRMWARE_CONFIG_H

#ifdef USB_MANUFACTURER
#define PRODUCT_MANUFACTURER USB_MANUFACTURER
#else
#define PRODUCT_MANUFACTURER    "Yonabe Factory"
#define USB_MANUFACTURER        PRODUCT_MANUFACTURER
#endif

#ifdef USB_PRODUCT
#define PRODUCT_NAME USB_PRODUCT
#else
#define PRODUCT_NAME    "SlappyBell"
#define USB_PRODUCT     PRODUCT_NAME
#endif

#define PRODUCT_VERSION "1.2.0"

#define SLOT_COUNT		6

#define PIN_NEOPIXEL	D3
#define PIN_I2S_BCLK	D9
#define PIN_I2S_LRC		D10
#define PIN_I2S_DOUT	D8
#define PIN_SD_MODE		D7

#define SSID_MAX_LENGTH		80
#define PASSWORD_MAX_LENGTH	80
#define MAX_LED_SEQUENCE_LENGTH 16

#define SERIAL_BUFFER_SIZE 128
#define BLE_MTU_SIZE       (128+3)
#define RECEIVE_BUFFER_SIZE 4096
#define RECEIVE_BUFFER_OVERFLOW_SIZE 256
#define MESSAGE_BUFFER_SIZE 256
#define DATA_CHUNK_TIMEOUT 2000

#define RESPONSE_PREFIX "[R@APM]"
#define NOTIFY_PREFIX "[N@APM]"

#endif //SLAPPYBELL_FIRMWARE_CONFIG_H