//
// Created by Yasuoki on 2025/12/16.
//

#ifndef SLAPPYBELL_FIRMWARE_CONFIG_H
#define SLAPPYBELL_FIRMWARE_CONFIG_H

#define PRODUCT_MANUFACTURER "Yonabe Factory"
#define PRODUCT_NAME "SlappyBell"
#define PRODUCT_VERSION "1.0.0"

#define USB_MANUFACTURER PRODUCT_MANUFACTURER
#define USB_PRODUCT      PRODUCT_NAME

#define SLOT_COUNT		6

#define PIN_NEOPIXEL	D3
#define PIN_I2S_BCLK	D9
#define PIN_I2S_LRC		D10
#define PIN_I2S_DOUT	D8
#define PIN_SD_MODE		D7

#define SSID_MAX_LENGTH		80
#define PASSWORD_MAX_LENGTH	80

#define RECV_BUFFER_SIZE 128
#define COMMAND_BUFFER_SIZE 256
#define FILE_BUFFER_SIZE 4096
#define MESSAGE_BUFFER_SIZE 256
#define MAX_LED_SEQUENCE_LENGTH 16

#define RESPONSE_PREFIX "[R@APM]"
#define NOTIFY_PREFIX "[N@APM]"

#endif //SLAPPYBELL_FIRMWARE_CONFIG_H